### ISSUE TITLE
missing main.py

### ISSUE THREAD

**Issue by jagad89** [NotTrueFalse/Captcha_solving#2]
You have mentioned to run the train model need to run `python main.py` once we put test images into `test` folder. but unable to find the `main.py` in the repo

**Comment by NotTrueFalse** [comment]
Done in this [commit](https://github.com/NotTrueFalse/Captcha_solving/commit/6177342e7005140c897501cd14fbd9eea23fc176)

**Comment by jagad89** [comment]
Thank you. I am trying to train a model on some captcha. I couldn't connect you on discord.

**Comment by NotTrueFalse** [comment]
discord :  enderty
